Add Travis badge
teiid/teiid-language-server pull request #7
Opened 2020-03-16 17:14 UTC by apupier

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

2020-03-17 13:56 UTC, apupier commented
badge can be seen on https://github.com/apupier/teiid-language-server/tree/AddTravisBadge
![Screenshot from 2020-03-17 14-56-34](https://user-images.githubusercontent.com/1105127/76863263-86256180-685f-11ea-9e91-ff53ca1919da.png)

2020-03-25 10:32 UTC, lhein commented
![image](https://user-images.githubusercontent.com/435853/77527362-44626f80-6e8c-11ea-8960-57df59a0fe10.png)

2020-03-25 10:33 UTC, lhein commented on README.md
> +![Build Status](https://travis-ci.org/teiid/teiid-language-server.svg?branch=master)](https://travis-ci.org/teiid/teiid-language-server)
something wrong with your brackets

2020-03-25 12:05 UTC, rareddy approved these changes
LGTM

2020-03-25 12:08 UTC, lhein requested changes
there seems to be an issue with the brackets

2020-03-25 14:04 UTC, apupier commented on README.md
> +![Build Status](https://travis-ci.org/teiid/teiid-language-server.svg?branch=master)](https://travis-ci.org/teiid/teiid-language-server)
well spotted. I badly resolved conflicts.

2020-03-25 14:04 UTC, apupier commented on README.md
> +![Build Status](https://travis-ci.org/teiid/teiid-language-server.svg?branch=master)](https://travis-ci.org/teiid/teiid-language-server)
this is fine again when accessing  https://github.com/apupier/teiid-language-server/tree/AddTravisBadge

2020-03-25 14:19 UTC, lhein approved these changes

2020-03-25 14:20 UTC, merged